# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beeswax/augment/augmentor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from beeswax.openrtb import openrtb_pb2 as beeswax_dot_openrtb_dot_openrtb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='beeswax/augment/augmentor.proto',
  package='augment',
  syntax='proto2',
  serialized_pb=_b('\n\x1f\x62\x65\x65swax/augment/augmentor.proto\x12\x07\x61ugment\x1a\x1d\x62\x65\x65swax/openrtb/openrtb.proto\"<\n\x10\x41ugmentorRequest\x12(\n\x0b\x62id_request\x18\x01 \x01(\x0b\x32\x13.openrtb.BidRequest\"\xcf\x01\n\x11\x41ugmentorResponse\x12\x34\n\x08segments\x18\x01 \x03(\x0b\x32\".augment.AugmentorResponse.Segment\x12\x38\n\x0e\x64ynamic_macros\x18\x02 \x03(\x0b\x32 .augment.AugmentorResponse.Macro\x1a$\n\x07Segment\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a$\n\x05Macro\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB\x15\n\x13\x63om.beeswax.augment')
  ,
  dependencies=[beeswax_dot_openrtb_dot_openrtb__pb2.DESCRIPTOR,])




_AUGMENTORREQUEST = _descriptor.Descriptor(
  name='AugmentorRequest',
  full_name='augment.AugmentorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bid_request', full_name='augment.AugmentorRequest.bid_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=135,
)


_AUGMENTORRESPONSE_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='augment.AugmentorResponse.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='augment.AugmentorResponse.Segment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='augment.AugmentorResponse.Segment.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=307,
)

_AUGMENTORRESPONSE_MACRO = _descriptor.Descriptor(
  name='Macro',
  full_name='augment.AugmentorResponse.Macro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='augment.AugmentorResponse.Macro.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='augment.AugmentorResponse.Macro.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=345,
)

_AUGMENTORRESPONSE = _descriptor.Descriptor(
  name='AugmentorResponse',
  full_name='augment.AugmentorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='augment.AugmentorResponse.segments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_macros', full_name='augment.AugmentorResponse.dynamic_macros', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUGMENTORRESPONSE_SEGMENT, _AUGMENTORRESPONSE_MACRO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=345,
)

_AUGMENTORREQUEST.fields_by_name['bid_request'].message_type = beeswax_dot_openrtb_dot_openrtb__pb2._BIDREQUEST
_AUGMENTORRESPONSE_SEGMENT.containing_type = _AUGMENTORRESPONSE
_AUGMENTORRESPONSE_MACRO.containing_type = _AUGMENTORRESPONSE
_AUGMENTORRESPONSE.fields_by_name['segments'].message_type = _AUGMENTORRESPONSE_SEGMENT
_AUGMENTORRESPONSE.fields_by_name['dynamic_macros'].message_type = _AUGMENTORRESPONSE_MACRO
DESCRIPTOR.message_types_by_name['AugmentorRequest'] = _AUGMENTORREQUEST
DESCRIPTOR.message_types_by_name['AugmentorResponse'] = _AUGMENTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AugmentorRequest = _reflection.GeneratedProtocolMessageType('AugmentorRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUGMENTORREQUEST,
  __module__ = 'beeswax.augment.augmentor_pb2'
  # @@protoc_insertion_point(class_scope:augment.AugmentorRequest)
  ))
_sym_db.RegisterMessage(AugmentorRequest)

AugmentorResponse = _reflection.GeneratedProtocolMessageType('AugmentorResponse', (_message.Message,), dict(

  Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), dict(
    DESCRIPTOR = _AUGMENTORRESPONSE_SEGMENT,
    __module__ = 'beeswax.augment.augmentor_pb2'
    # @@protoc_insertion_point(class_scope:augment.AugmentorResponse.Segment)
    ))
  ,

  Macro = _reflection.GeneratedProtocolMessageType('Macro', (_message.Message,), dict(
    DESCRIPTOR = _AUGMENTORRESPONSE_MACRO,
    __module__ = 'beeswax.augment.augmentor_pb2'
    # @@protoc_insertion_point(class_scope:augment.AugmentorResponse.Macro)
    ))
  ,
  DESCRIPTOR = _AUGMENTORRESPONSE,
  __module__ = 'beeswax.augment.augmentor_pb2'
  # @@protoc_insertion_point(class_scope:augment.AugmentorResponse)
  ))
_sym_db.RegisterMessage(AugmentorResponse)
_sym_db.RegisterMessage(AugmentorResponse.Segment)
_sym_db.RegisterMessage(AugmentorResponse.Macro)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.beeswax.augment'))
# @@protoc_insertion_point(module_scope)
